### ISSUE TITLE
mimmi20___browscap-js yb analysis

### ISSUE THREAD

**Issue by keheliya** [project-kotinos/issues#43]
Add a yb configuration file to https://github.com/project-kotinos/mimmi20___browscap-js
Instuctions are here: https://github.com/project-kotinos/root/blob/master/README.md 
If you come across problems, add them as comments to this issue.

**Comment by nictuku** [comment]
I can't really move forward with this unless we support something like this:

```
build_targets:
  - name: default
  - name: test_9_11
    dependencies:
      build:
       - node:9.11
    commands:
      # Travis runs this by default
      - npm install
      - npm test
```

I could potentially create sub-directories with .yourbase.yml files with each dependency and then build things that way. Seems gross.
